import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#191b23',
        'tertiary-fixed': '#ffdcc6',
        'on-tertiary-container': '#461f00',
        'on-tertiary-fixed': '#311400',
        error: '#ffb4ab',
        'surface-dim': '#10131a',
        'surface-container': '#1d2027',
        outline: '#8c909f',
        'surface-tint': '#adc6ff',
        'inverse-on-surface': '#2e3038',
        'secondary-fixed-dim': '#ffb95f',
        'on-secondary-fixed-variant': '#653e00',
        primary: '#adc6ff',
        'on-surface-variant': '#c2c6d6',
        'surface-container-highest': '#32353c',
        'secondary-container': '#ee9800',
        'surface-variant': '#32353c',
        'inverse-surface': '#e1e2ec',
        'outline-variant': '#424754',
        'primary-fixed': '#d8e2ff',
        'on-error': '#690005',
        'surface-container-high': '#272a31',
        'surface-container-lowest': '#0b0e15',
        'on-error-container': '#ffdad6',
        'on-tertiary-fixed-variant': '#723600',
        'primary-fixed-dim': '#adc6ff',
        'tertiary-fixed-dim': '#ffb786',
        secondary: '#ffb95f',
        'secondary-fixed': '#ffddb8',
        'on-secondary': '#472a00',
        'on-surface': '#e1e2ec',
        background: '#10131a',
        'on-secondary-container': '#5b3800',
        tertiary: '#ffb786',
        'on-primary-fixed-variant': '#004395',
        'surface-bright': '#363941',
        'on-secondary-fixed': '#2a1700',
        'tertiary-container': '#df7412',
        'on-background': '#e1e2ec',
        'on-tertiary': '#502400',
        'primary-container': '#4d8eff',
        'on-primary-container': '#00285d',
        'on-primary-fixed': '#001a42',
        'inverse-primary': '#005ac2',
        surface: '#10131a',
        'error-container': '#93000a',
        'on-primary': '#002e6a',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        gutter: '24px',
        md: '24px',
        lg: '40px',
        xs: '4px',
        xl: '64px',
        sm: '12px',
        margin: '32px',
      },
      maxWidth: {
        xs: '20rem',
        sm: '24rem',
        md: '28rem',
        lg: '32rem',
        xl: '36rem',
        '2xl': '42rem',
        '3xl': '48rem',
        '4xl': '56rem',
        '5xl': '64rem',
        '6xl': '72rem',
        '7xl': '80rem',
      },
      fontFamily: {
        'body-sm': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-xl': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        headline: ['Inter', 'sans-serif'],
        display: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};

export default config;
